"""remove speciality and target score

Revision ID: 0e5bf6a2efa1
Revises: e744823e6dfe
Create Date: 2026-09-21 11:38:43.962178
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '0e5bf6a2efa1'
down_revision: Union[str, Sequence[str], None] = 'e744823e6dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_streaks', 'target_score')
    op.drop_column('users', 'target_bac_score')
    op.drop_column('users', 'speciality')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('speciality', mysql.ENUM('math', 'technique', 'scientifique'), nullable=True))
    op.add_column('users', sa.Column('target_bac_score', mysql.FLOAT(), nullable=False))
    op.add_column('study_streaks', sa.Column('target_score', mysql.FLOAT(), nullable=False))
    # ### end Alembic commands ###
