"""rename doctors table to users

Revision ID: 57728c5527b8
Revises: 0001_initial
Create Date: 2026-09-01 21:15:43.273544
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '57728c5527b8'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table('users'):
        op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('fullName', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('speciality', sa.Enum('math', 'technique', 'scientifique', name='speciality_enum', create_type=False), nullable=True),
        sa.Column('stream', sa.String(length=255), nullable=True),
        sa.Column('target_bac_score', sa.Float(), nullable=False),
        sa.Column('is_admin', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
        )
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    if inspector.has_table('doctors'):
        op.drop_index('ix_doctors_id', table_name='doctors')
        op.drop_table('doctors')

    for table_name, column_name in [
        ('exam_attempts', 'user_id'),
        ('exercise_attempts', 'user_id'),
        ('study_sessions', 'user_id'),
        ('study_streaks', 'user_id'),
        ('user_chapter_progress', 'user_id'),
    ]:
        try:
            op.drop_constraint(f'{table_name}_{column_name}_fkey', table_name, type_='foreignkey')
        except Exception:
            pass
        try:
            op.create_foreign_key(f'fk_{table_name}_{column_name}_users', table_name, 'users', [column_name], ['id'], ondelete='CASCADE')
        except Exception:
            pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_chapter_progress', type_='foreignkey')
    op.create_foreign_key('user_chapter_progress_user_id_fkey', 'user_chapter_progress', 'doctors', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'study_streaks', type_='foreignkey')
    op.create_foreign_key('study_streaks_user_id_fkey', 'study_streaks', 'doctors', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'study_sessions', type_='foreignkey')
    op.create_foreign_key('study_sessions_user_id_fkey', 'study_sessions', 'doctors', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'exercise_attempts', type_='foreignkey')
    op.create_foreign_key('exercise_attempts_user_id_fkey', 'exercise_attempts', 'doctors', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'exam_attempts', type_='foreignkey')
    op.create_foreign_key('exam_attempts_user_id_fkey', 'exam_attempts', 'doctors', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_table('doctors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fullName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('speciality', postgresql.ENUM('math', 'technique', 'scientifique', name='speciality_enum'), autoincrement=False, nullable=True),
    sa.Column('stream', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('target_bac_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='doctors_pkey'),
    sa.UniqueConstraint('email', name='doctors_email_key')
    )
    op.create_index('ix_doctors_id', 'doctors', ['id'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
