"""add exercises table

Revision ID: d3cb09aaa07c
Revises: b7c8d9e0f1a2
Create Date: 2026-09-21 09:59:03.759309
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'd3cb09aaa07c'
down_revision: Union[str, Sequence[str], None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.String(length=100), nullable=False),
    sa.Column('concept_id', sa.String(length=100), nullable=True),
    sa.Column('exercise_type', sa.Enum('exercise', 'bac', name='exercise_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='exercise_difficulty_enum'), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('bac_year', sa.Integer(), nullable=True),
    sa.Column('bac_session', sa.String(length=20), nullable=True),
    sa.Column('bac_stream', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_chapter_id'), 'exercises', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_exercises_concept_id'), 'exercises', ['concept_id'], unique=False)
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_concept_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_chapter_id'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
