"""add curriculum, quizzes, tests, community, progress modules

Revision ID: e744823e6dfe
Revises: d3cb09aaa07c
Create Date: 2026-09-21 11:09:04.909098
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'e744823e6dfe'
down_revision: Union[str, Sequence[str], None] = 'd3cb09aaa07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_fr', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stream', sa.String(length=255), nullable=True),
    sa.Column('total_chapters', sa.Integer(), nullable=False),
    sa.Column('total_hours', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_fr', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('stream', sa.String(length=255), nullable=True),
    sa.Column('icon_name', sa.String(length=100), nullable=True),
    sa.Column('bac_weight', sa.String(length=100), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(length=50), nullable=True),
    sa.Column('weeks', sa.String(length=50), nullable=True),
    sa.Column('official_axis', sa.String(length=255), nullable=True),
    sa.Column('total_weekly_hours', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_subject_id'), 'chapters', ['subject_id'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_caption', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('has_best_answer', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_posts_author_id'), 'community_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_community_posts_id'), 'community_posts', ['id'], unique=False)
    op.create_table('community_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('post', 'answer', 'reply', name='community_target_type_enum'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='uq_community_vote')
    )
    op.create_index(op.f('ix_community_votes_id'), 'community_votes', ['id'], unique=False)
    op.create_index(op.f('ix_community_votes_user_id'), 'community_votes', ['user_id'], unique=False)
    op.create_table('lesson_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.String(length=100), nullable=False),
    sa.Column('video_watched_seconds', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concept_id', name='uq_lesson_completion')
    )
    op.create_index(op.f('ix_lesson_completions_concept_id'), 'lesson_completions', ['concept_id'], unique=False)
    op.create_index(op.f('ix_lesson_completions_id'), 'lesson_completions', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_completions_user_id'), 'lesson_completions', ['user_id'], unique=False)
    op.create_table('community_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('is_best_answer', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_answers_author_id'), 'community_answers', ['author_id'], unique=False)
    op.create_index(op.f('ix_community_answers_id'), 'community_answers', ['id'], unique=False)
    op.create_index(op.f('ix_community_answers_post_id'), 'community_answers', ['post_id'], unique=False)
    op.create_table('concepts',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('chapter_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_fr', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('week_date', sa.String(length=50), nullable=True),
    sa.Column('month', sa.String(length=50), nullable=True),
    sa.Column('official_hours', sa.Float(), nullable=True),
    sa.Column('axis_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepts_chapter_id'), 'concepts', ['chapter_id'], unique=False)
    op.create_table('community_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['community_answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_replies_answer_id'), 'community_replies', ['answer_id'], unique=False)
    op.create_index(op.f('ix_community_replies_author_id'), 'community_replies', ['author_id'], unique=False)
    op.create_index(op.f('ix_community_replies_id'), 'community_replies', ['id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('concept_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('video_title', sa.String(length=255), nullable=True),
    sa.Column('video_duration', sa.String(length=20), nullable=True),
    sa.Column('video_thumbnail', sa.String(length=500), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('objectives', sa.JSON(), nullable=True),
    sa.Column('theory', sa.JSON(), nullable=True),
    sa.Column('worked_examples', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_concept_id'), 'lessons', ['concept_id'], unique=True)
    op.create_table('mini_tests',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('concept_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mini_tests_concept_id'), 'mini_tests', ['concept_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('concept_id', sa.String(length=100), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_math', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_option_id', sa.String(length=100), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('explanation_math', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_concept_id'), 'quiz_questions', ['concept_id'], unique=False)
    op.create_table('quiz_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.String(length=100), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_submissions_concept_id'), 'quiz_submissions', ['concept_id'], unique=False)
    op.create_index(op.f('ix_quiz_submissions_id'), 'quiz_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_submissions_user_id'), 'quiz_submissions', ['user_id'], unique=False)
    op.create_table('test_questions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('concept_id', sa.String(length=100), nullable=False),
    sa.Column('chapter_id', sa.String(length=100), nullable=False),
    sa.Column('concept_name', sa.String(length=255), nullable=True),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_math', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_option_id', sa.String(length=100), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('explanation_math', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['mini_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_questions_test_id'), 'test_questions', ['test_id'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('concept_id', sa.String(length=100), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('concept_breakdown', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['mini_tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
    op.create_index(op.f('ix_test_results_test_id'), 'test_results', ['test_id'], unique=False)
    op.create_index(op.f('ix_test_results_user_id'), 'test_results', ['user_id'], unique=False)
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('reputation', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('badges', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'badges')
    op.drop_column('users', 'reputation')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_test_results_user_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_test_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_test_questions_test_id'), table_name='test_questions')
    op.drop_table('test_questions')
    op.drop_index(op.f('ix_quiz_submissions_user_id'), table_name='quiz_submissions')
    op.drop_index(op.f('ix_quiz_submissions_id'), table_name='quiz_submissions')
    op.drop_index(op.f('ix_quiz_submissions_concept_id'), table_name='quiz_submissions')
    op.drop_table('quiz_submissions')
    op.drop_index(op.f('ix_quiz_questions_concept_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_mini_tests_concept_id'), table_name='mini_tests')
    op.drop_table('mini_tests')
    op.drop_index(op.f('ix_lessons_concept_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_community_replies_id'), table_name='community_replies')
    op.drop_index(op.f('ix_community_replies_author_id'), table_name='community_replies')
    op.drop_index(op.f('ix_community_replies_answer_id'), table_name='community_replies')
    op.drop_table('community_replies')
    op.drop_index(op.f('ix_concepts_chapter_id'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_index(op.f('ix_community_answers_post_id'), table_name='community_answers')
    op.drop_index(op.f('ix_community_answers_id'), table_name='community_answers')
    op.drop_index(op.f('ix_community_answers_author_id'), table_name='community_answers')
    op.drop_table('community_answers')
    op.drop_index(op.f('ix_lesson_completions_user_id'), table_name='lesson_completions')
    op.drop_index(op.f('ix_lesson_completions_id'), table_name='lesson_completions')
    op.drop_index(op.f('ix_lesson_completions_concept_id'), table_name='lesson_completions')
    op.drop_table('lesson_completions')
    op.drop_index(op.f('ix_community_votes_user_id'), table_name='community_votes')
    op.drop_index(op.f('ix_community_votes_id'), table_name='community_votes')
    op.drop_table('community_votes')
    op.drop_index(op.f('ix_community_posts_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_author_id'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_chapters_subject_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_table('subjects')
    # ### end Alembic commands ###
