"""exercises rich fields and external id

Revision ID: edf530054781
Revises: 0e5bf6a2efa1
Create Date: 2026-09-21 15:36:13.087426
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'edf530054781'
down_revision: Union[str, Sequence[str], None] = '0e5bf6a2efa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.add_column('exercises', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('exercises', sa.Column('question_math', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('answer_type', sa.String(length=30), nullable=True))
    op.add_column('exercises', sa.Column('options', sa.JSON(), nullable=True))
    op.add_column('exercises', sa.Column('correct_answer', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('accepted_answers', sa.JSON(), nullable=True))
    op.add_column('exercises', sa.Column('solution_steps', sa.JSON(), nullable=True))
    op.add_column('exercises', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('hint', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('sub_questions', sa.JSON(), nullable=True))
    op.add_column('exercises', sa.Column('official_solution', sa.JSON(), nullable=True))
    op.create_unique_constraint('uq_exercises_external_id', 'exercises', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_exercises_external_id', 'exercises', type_='unique')
    op.drop_column('exercises', 'official_solution')
    op.drop_column('exercises', 'sub_questions')
    op.drop_column('exercises', 'hint')
    op.drop_column('exercises', 'explanation')
    op.drop_column('exercises', 'solution_steps')
    op.drop_column('exercises', 'accepted_answers')
    op.drop_column('exercises', 'correct_answer')
    op.drop_column('exercises', 'options')
    op.drop_column('exercises', 'answer_type')
    op.drop_column('exercises', 'question_math')
    op.drop_column('exercises', 'number')
    op.drop_column('exercises', 'external_id')
    # ### end Alembic commands ###
